### ISSUE TITLE
Treat `;` (End of statement) as an EOF in the lexer

### ISSUE THREAD

**Issue by kamikazechaser** [lmittmann/w3#119]
It is common for event signatures definitions in Solidity to end in a semicolon. A test such as:

```go
		{
			Signature: "Transfer(address,address,uint256);",
			WantEvent: &w3.Event{
				Signature: "Transfer(address,address,uint256)",
				Topic0:    w3.H("0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"),
			},
		},
```

should pass.

However this test will result in a panic. I think a quick fix is to assume a semicolon is an EOF type character in the lexer.

**Comment by lmittmann** [comment]
The Topic0 is derived from the Signature. A Semicolon in the signature would result in the wrong hash (Topic 0). Maybe use `strings.TrimSuffix` instead.

close #120

**Comment by kamikazechaser** [comment]
It would be better for it to be handled within the library for better DX. But either approach is fine (since it is now documented here). Thanks.
