### ISSUE TITLE
The call trace doesnt not include RevertReason 

### ISSUE THREAD

**Issue by kant777** [lmittmann/w3#123]
This does not include `RevertReason`  https://github.com/lmittmann/w3/blob/main/module/debug/call_trace.go#L30-L41 according the spec here https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers .  see the calltracer section

**Comment by lmittmann** [comment]
PRs welcome

**Comment by kamikazechaser** [comment]
There is a workaround this by "simulating" the tx. Infact it is better as it doesn't burn the usually expensive trace credits on 3rd party RPC providers.

https://github.com/grassrootseconomics/celoutils/blob/v3/simulate.go

**Comment by krishnateja262** [comment]
@lmittmann i am interested to work on this, lmk if this issue is open for contributions

**Comment by lmittmann** [comment]
fixed in #173
