### ISSUE TITLE
Allow overriding the default geth `rpc.Client`

### ISSUE THREAD

**Issue by kamikazechaser** [lmittmann/w3#124]
w3 uses the default client that geth provides:

https://github.com/lmittmann/w3/blob/491929077fac8660b613d4d4f390d427d7f323be/client.go#L47

However, geth also provides finer control over some transports e.g.

https://github.com/ethereum/go-ethereum/blob/14cc967d1964d3366252193cadd4bfcb4c927ac1/rpc/http.go#L132

It would be nice to have a feature where this can be overridden through a method on the w3 `Client` itself e.g.

```go
func (c *Client ) SetCustomRPCClient(client *rpc.Client)`
```

If this is within scope, I can send a PR.

**Comment by lmittmann** [comment]
You can use [`w3.NewClient`](https://pkg.go.dev/github.com/lmittmann/w3#NewClient) to create a new `w3.Client` from your custom `go-ethereum/rpc.Client`.

**Comment by kamikazechaser** [comment]
Ah missed that. That is exactly what I need. Thanks!
