### ISSUE TITLE
[FEATURE] Handle individual batch call errors the same way return values are being handled right now

### ISSUE THREAD

**Issue by rtunazzz** [lmittmann/w3#18]
# Introduction
If one of the calls from a batch request fails, return values from the following calls won't be returned (even if they are executed successfully).

I personally think it would be better if w3 returned an error when the batch request fails (network error, etc.) but NOT if one of the calls inside the batch request fails. Something similar to how go-ethereum handles their batch request calls.

# Proposal
I propose we add a `.Errors` method to the `CallFuncFactory`, allowing us to specify where the error would get saved the same `.Returns` does.

## Example
Consider the following snippet:
```go
err := client.Call(
	eth.CallFunc(nonExistentFunc, w3.A("0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2")).
		Errors(targetErr1).
		Returns(res1),
	eth.CallFunc(funcBalanceOf, w3.A("0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"), w3.A("0x000000000000000000000000000000000000c0Fe")).
		Errors(targetErr2).
		Returns(res2),
)
```

The caller would then be able to check the particular call errors via the `targetErr1` and `targetErr2` variables in this particular example. If `targetErr2 == nil`, I would then expect `res2` hold the expected return value.

---

Thoughts?

**Comment by lmittmann** [comment]
I agree, the current error handling is not ideal. However, I would prefer to return something like
```go
type CallErrors []error
```
in `Client.Call` instead. The success of an individual call could than be checked by its index.

**Comment by rtunazzz** [comment]
Sure, that works!

I was considering that option as well but wasn't sure which idea would be more idiomatic.. 🙂

**Comment by lmittmann** [comment]
Call and CallCtx now returns the CallErrors type if the handling of one or more RPC responses failed. You can try this by importing the head instead of the v0.9.1. I will include it in a release after some playing around with it.

You need to check for an error and if that error is of `CallErrors` type. E.g.:
```go
if err != nil {
  callErrs, ok := err.(w3.CallErrors)
  ...
}
```

**Comment by lmittmann** [comment]
This is now part of `v0.10.0`
