### ISSUE TITLE
Allow BlockByNumber to only return transaction hashes and not full transactions

### ISSUE THREAD

**Issue by OscBacon** [lmittmann/w3#20]
Hi, I noticed that in refactoring the HeaderByNumber, and dropping the RPCHeader type, I am now not able to get a header with only the transaction hashes.
It would help if either HeaderByNumber could return either a types.Header or types.Block, or for BlockByNumber to return a hydrated or not hydrated list of transactions in the block

**Comment by lmittmann** [comment]
The `types.Block` type does not support tx hashes only. If you use `eth.BlockByNumber(...)` you could access the transactions hashes though. E.g. `block.Transactions()[0].Hash()`

**Comment by OscBacon** [comment]
You should be able to parse eth_getBlockByNumber to only get the transaction hash though? The aim is to avoid querying entire transactions when all you need is the transaction hash

**Comment by lmittmann** [comment]
The problem is, that you can not decode the result of `["eth_getBlockByNumber", false]` into `types.Block`, because types.Block only supports full transactions. The only reason the tests for your PR #21 don't fail is that there is no test case for a block with transactions. 

Sorry for breaking some of your code. If you really need that extra efficiency I suggest that you take the old `RPCHeader` type and `HeaderByNumber` func and include it directly in your code. `w3` is designed to be modular so that you are able to use custom RPC method bindings alongside the bindings in `w3/modules/...`.

**Comment by OscBacon** [comment]
Should have marked the PR as [WIP] :) I did modify the tests but didn't take the time to try with the dehydrated transactions.
I tried looking at your v8.1.0, but had a bit of a hard time with the generics and factories.
When you did HeaderByNumber, and called returnraw, how were you obtaining the list of transaction hashes, and woud it be dfferent from just setting the transaction hash in the `types.Block` Transactions elements?

**Comment by sambarnes** [comment]
generally agree with the premise of this issue -- if there's information in the RPC response i'd want to be able to access it as i would in other clients/langs

i get the desire to stay close to the go-ethereum types, but also see a path forward with a header + simple string/common.Hash list

---

great lib so far tho :)

**Comment by lmittmann** [comment]
Hi @sambarnes, I generally agree with you. My problem is that I am limited in my resources to maintain this library and therefore do not want to diverge too much from go-ethereum. 

One of the key design aspects of the `w3.Client` is its extensibility to support custom rpc-method-bindings that can be used along the bindings implemented in this package. At this point I can't yet link you to a doc, but all you need to do is implement an `w3types.Caller` like here:
> https://github.com/lmittmann/w3/blob/61f5a928780428bb9f28e6d86e052755eb38a311/module/eth/get_block_by_number.go

If you (or anyone else) want to work on this and create a repo with method bindings to `getBlockBy{Number,Header}`, `getTransactionByHash` with the raw content returned by geth I am happy to help out if you have any questions.
