### ISSUE TITLE
It is possible CallFunc().Returns into struct?

### ISSUE THREAD

**Issue by EasySmoke** [lmittmann/w3#24]
There's my case: I need make a call with many output (like slot0) and when I try something like `c.Call(eth.CallFunc(w3.MustNewFunc("signature", "output fields"), address).Returns(&myStruct))`
I receive an error 
> invalid type: can not copy *big.Int to *myStruct

But ok, I could then map fields into a structure, but the problems start when I need make a multicall one function and the number of calls can be dynamic. Example: 
```
c.Call(
  eth.CallFunc(w3.MustNewFunc("signature", "output fields"), address1).Returns(???),
  eth.CallFunc(w3.MustNewFunc("signature", "output fields"), address2).Returns(???),
  eth.CallFunc(w3.MustNewFunc("signature", "output fields"), address3).Returns(???),
)
```
How make the correct return? Do I understand correctly that such cases are left out yet in the library interface/unfinished?

**Comment by lmittmann** [comment]
Tuples are in general supported by this package. However, there seems to be a bug that prevents tuple decoding of the call return data (#25).

Once this bug is resolved you will be able to access the slot0 like this:

```go
var (
	client    = w3.MustDial("https://rpc.ankr.com/eth")
	funcSlot0 = w3.MustNewFunc("slot0()", "(uint160 sqrtPriceX96, int24 tick, uint16 observationIndex, uint16 observationCardinality, uint16 observationCardinalityNext, uint8 feeProtocol, bool unlocked) slot0")
	addrPool  = w3.A("0x5777d92f208679DB4b9778590Fa3CAB3aC9e2168")
)

func main() {
	var res slot0
	if err := client.Call(
		eth.CallFunc(funcSlot0, addrPool).Returns(&res),
	); err != nil {
		fmt.Printf("Failed to fetch slot0: %v\n", err)
		return
	}

	fmt.Printf("Slot0: %+v\n", res)
}

type slot0 struct {
	SqrtPriceX96               *big.Int
	Tick                       int32
	ObservationIndex           uint16
	ObservationCardinality     uint16
	ObservationCardinalityNext uint16
	FeeProtocol                uint8
	Unlocked                   bool
}
```

For requests with a dynamic number of calls see [examples/scan_blocks](https://github.com/lmittmann/w3/tree/main/examples/scan_blocks).

**Comment by lmittmann** [comment]
The new release `v0.10.0` fixes the related issue
