### ISSUE TITLE
debug.CallTrace example

### ISSUE THREAD

**Issue by Auroter** [lmittmann/w3#37]
Could you provide an example of debug.CallTrace?  When attempting to use it, I receive the following error:

`err := e.client.Call(debug.CallTraceTx(txHash, w3types.State{}).Returns(&trace))`

`ERR = w3: call failed: the method debug_traceTransaction does not exist`

**Comment by kamikazechaser** [comment]
Are you running geth with `--http.api debug`? Might now work on other clients.

**Comment by Auroter** [comment]
Hey!  So I am not running the Geth console if that's what you mean.  I am just using ethclient.Dial() and w3.Dial() to connect to various blockchains in a go web application.  Is there a way to connect to a chain with Debug enabled without running the Geth console and maintaining a local node?  Seems extremely resource intensive if I want to support many different chains...

**Comment by kamikazechaser** [comment]
> Is there a way to connect to a chain with Debug enabled without running the Geth console and maintaining a local node?

No. Afaik very few 3rd party hosted nodes expose the debug api like QuickNode.

**Comment by Auroter** [comment]
Thanks for the quick responses!  If I wanted to run Geth in order to use the tracing in w3, how do I ensure the w3 client is connected to it?

**Comment by kamikazechaser** [comment]
Same way as usual, just change the RPC endpoint to your localhost/address where you host the geth instance.
