### ISSUE TITLE
Support Subscription

### ISSUE THREAD

**Issue by lmittmann** [lmittmann/w3#38]

**Comment by kamikazechaser** [comment]
If I may ask, is this feature meant to be a new websocket implementation or a wrapper over the existing ethclient?

**Comment by lmittmann** [comment]
The idea is to use the existing [`go-ethereum/rpc`](https://pkg.go.dev/github.com/ethereum/go-ethereum/rpc) implementation. The challenge is to be able to do the subscription in a batch call, so the `w3.Client` API does not need to be extended. This would require changes to `go-ethereum/rpc` though.

**Comment by rtunazzz** [comment]
This would be nice!

I'd also like to suggest support for both WSS & HTTP implementations (i.e. using `eth_subscribe` where possible & replace with polling for RPCs that do not support that method). This would be identical with [how ethers-js handles this](https://github.com/ethers-io/ethers.js/blob/39315288bee6f116e362e70c00f999ae669dd462/src.ts/providers/subscriber-polling.ts).

**Comment by lmittmann** [comment]
Unfortunately I don't see a feasible path to creating a subscription within a batch request using `go-ethereum/rpc`. Idea's are  welcome!
