### ISSUE TITLE
Adding proxies to client requests

### ISSUE THREAD

**Issue by vodves-vodves** [lmittmann/w3#51]
How about adding proxy requests to the client? It's just that free RPCs have limitations. With a proxy, this problem can be solved.

**Comment by kamikazechaser** [comment]
You can create your own `http.Client` that has the proxy config. Then pass that when creating a new `*rpc.Client` with `rpc.DialHTTPWithClient`. Then use it with `w3.NewClient`.

**Comment by vodves-vodves** [comment]
> You can create your own `http.Client` that has the proxy config. Then pass that when creating a new `*rpc.Client` with `rpc.DialHTTPWithClient`. Then use it with `w3.NewClient`.
Thanks, I'll try to do that.

**Comment by lmittmann** [comment]
If you need the client to respect rate limits you can also try out the experimental support for rate limiting in #50.

**Comment by vodves-vodves** [comment]
> If you need the client to respect rate limits you can also try out the experimental support for rate limiting in #50.

how to download?

**Comment by lmittmann** [comment]
`go get github.com/lmittmann/w3@main`. It will also be included in the next release.

**Comment by vodves-vodves** [comment]
> `go get github.com/lmittmann/w3@main`. It will also be included in the next release. You can find an example here: https://github.com/lmittmann/w3/blob/main/client_test.go#L298-L305

thanks

**Comment by kamikazechaser** [comment]
What editor/IDE are you using? Could you post a snippet of the go.mod file.

**Comment by kamikazechaser** [comment]
You are on the April 23rd commit. Try the command with the `-u` flag.

**Comment by vodves-vodves** [comment]
> You are on the April 23rd commit. Try the command with the `-u` flag.

I already tried that, nothing changes)
