### ISSUE TITLE
How does MustNewFunc handle functions that return multiple values?

### ISSUE THREAD

**Issue by MasterShake20** [lmittmann/w3#62]
I'm trying to read a smart contract that has a getReserves() function that returns 3 values - reserve0, reserve1 and blockTimestampLast.  How should that get coded?

```
    getReserves := w3.MustNewFunc("getReserves()", "uint112, uint112, uint32")
    var reserves big.Int 

    err := client.Call(eth.CallFunc(getReserves, tokenPairAddress).Returns(&reserves))
    if err != nil {
        log.Fatal(err)
    }
```

The above code is getting the following result:
`{false [12569833997705177805 642440]}`

**Comment by lmittmann** [comment]
Hi @MasterShake20 , the function declaration looks good. Decoding returns works analogues to encoding arguments - each argument/return needs to be mapped to a single value. In your case you have three returns:

```go
var (
	reserve0                   *big.Int
	reserve1                   *big.Int
	blockTimestampLast uint32
)
err := client.Call(
	eth.CallFunc(getReserves, pair).Returns(&reserve0, &reserve1, &blockTimestampLast),
)
```

In case you don't need the value of e.g. `blockTimestampLast` you can also ignore that value by passing `nil` for it instead:

```go
var (
	reserve0 *big.Int
	reserve1 *big.Int
)
err := client.Call(
	eth.CallFunc(getReserves, pair).Returns(&reserve0, &reserve1, nil),
)
```

Feel free to reopen the issue in case you have another question in regards to this.
