### ISSUE TITLE
Would MustNewEvent be used for listening for transaction events from a contract?

### ISSUE THREAD

**Issue by MasterShake20** [lmittmann/w3#63]
If so is there an example somewhere of how to implement? 

Thanks

**Comment by lmittmann** [comment]
`w3` does not support subscriptions yet (#38). However, the `w3.Event` can be used to decode an event-log retrieved from a tx receipt (`eth.TxReceipt(...)` or filter quer (`eth.Logs(...)`). Event decoding works analogous to function decoding: you pass the log, followed by the events arguments to set the values of the passed args: [`Event.DecodeArgs`](https://pkg.go.dev/github.com/lmittmann/w3@v0.13.0#Event.DecodeArgs).
