### ISSUE TITLE
Accomodate for Ganache negative transaction cost during debug_traceTransaction

### ISSUE THREAD

**Issue by dimi101** [lmittmann/w3#64]
As per https://github.com/trufflesuite/ganache/issues/277 and https://github.com/trufflesuite/ganache/pull/578 a Ganache blockchain may report negative gas cost for a REVERT or RETURN EVM command.

The StructLog struct (module/debug/trace.go) for the result of the debug_traceTransaction RPC is using a uint to save the gas resulting in an error.

**Comment by lmittmann** [comment]
The RPC-methods supported by this package are meant to support go-ethereum which can not report negative gas costs. Unfortunately the more advanced RPC-methods like tracing differ a lot between nodes and testing frameworks in their output format. 

You can do two things:
1. implement a custom `debug_traceTransaction` for Ganach. `w3` is extendable with custom method bindings. You need to implement the [`w3types.Caller`](https://pkg.go.dev/github.com/lmittmann/w3/w3types#Caller) interface. See e.g. https://github.com/lmittmann/w3/blob/v0.13.0/module/eth/call.go#L98 as reference.
2. play with the [w3vm](https://github.com/lmittmann/w3/tree/w3vm) branch which will bring something like Ganache, but pure Go and super fast with state forking via RPC to `w3`. It allows tracing using any [vm.EVMLogger](https://pkg.go.dev/github.com/ethereum/go-ethereum/core/vm#EVMLogger) implementation. However, this is still experimental and only "documented" here: https://pkg.go.dev/github.com/lmittmann/w3@v0.13.1-0.20230731131337-81c2e8d06cf9/w3vm

**Comment by dimi101** [comment]
Thank you very much for your very detailed reply.
That w3vm branch looks great and so does the ease in extending through w3types.Caller.
