### ISSUE TITLE
NewFunc fails when signature contains tuples without names

### ISSUE THREAD

**Issue by joel-u410** [lmittmann/w3#67]
Example code that illustrates the issue:

```go
w3.MustNewFunc("test((address, uint256))", "")
```

Result:
```
panic: w3: invalid ABI: syntax error: unexpected ",", want name
```

I have function signatures without names, e.g. as returned by openchain.xyz, and I would like to be able to decode args from them. I don't care as much about actually extracting the tuple values, and will likely just provide `nil` for any tuples in the `args` I pass to `DecodeArgs`. But, I would still like the function to be successfully created.

That said, I am working on implementing this in such a way that you can decode tuples into `[]any` slices, which will allow unnamed tuple fields to be supported and actually decodable. I'll open the PR soon!

**Comment by lmittmann** [comment]
The reason tuple arguments must be named is that they are decoded into a `struct` by `go-ethereum/accounts/abi`, which `w3` uses under the hood.

I'm not 100% convinced, that adding an alternative decoding for tuple into slices is a good idea. The decoding in `w3/internal/abi` is already super complex and I don't really want to add more complexity.

How about achieving the same goal by adding default attribute names for tuples during parsing, e.g. `arg0`, `arg1`, ... `argN`? However, a tuple should either be fully named, or contain no names at all.

**Comment by joel-u410** [comment]
My MR actually does add default attribute names similar to what you've suggested -- although I chose less friendly names `__tuple%d` instead of `arg%d` since I wanted to have less chance they would collide with legitimate names. But, on second thought, that's probably not a great concern. Would you prefer I change it to `arg%d`?

My reasoning for allowing decoding into `[]any` as an additional option was because I'm attempting to build a general-purpose trace parser, and I am generating argument placeholders programmatically based on reading the signature and splitting the types. In my case, I don't care about tuple names, but just generally want to capture the values -- it's much simpler for me to recognize "this argument is a tuple" and produce a `[]any` placeholder rather than inspect the tuple and dynamically generate a struct (using `reflect` presumably) to hold all of its fields.

**Comment by joel-u410** [comment]
Hopefully, when you look at [my MR](https://github.com/lmittmann/w3/pull/68/files#diff-674d887bd6aa473f82acb14e11cc912f44a661169e7158fbf169a9ae5a7a205cR140), you'll find it doesn't introduce _too_ much complexity to the decoder 🙁

**Comment by lmittmann** [comment]
Yes, I saw your PR. Maybe your usecase is a little to specific to be covered by this package. Have you thought about adding dummy arg names to the signature string so it can be parsed by `w3.NewFunc`?

Regarding your usecase:
* [Func](https://pkg.go.dev/github.com/lmittmann/w3#Func) actually exposes the `go-ethereum/accounts/abi.Arguments` of the functions args and returns. which will give you all decoded values (including tuples) in a `[]any` slice, see [`Arguments.Unpack`](https://pkg.go.dev/github.com/ethereum/go-ethereum/accounts/abi#Arguments.Unpack).
* Since you are doing trace related stuff, you might be interested into the not yet release code in the [`w3vm`](https://github.com/lmittmann/w3/tree/w3vm) branch which adds VM message simulation with mainnet forking capabilities and also support for passing one or more [vm.EVMLogger](https://pkg.go.dev/github.com/ethereum/go-ethereum/core/vm#EVMLogger) implementations. Some "documentation" is here: https://pkg.go.dev/github.com/lmittmann/w3@v0.13.1-0.20230816200810-3e86a991f0c4/w3vm

**Comment by joel-u410** [comment]
> [Func](https://pkg.go.dev/github.com/lmittmann/w3#Func) actually exposes the go-ethereum/accounts/abi.Arguments of the functions args and returns. which will give you all decoded values (including tuples) in a []any slice, see [Arguments.Unpack](https://pkg.go.dev/github.com/ethereum/go-ethereum/accounts/abi#Arguments.Unpack).

Oh, interesting! I'll look into that -- thanks.

I did try adding dummy arg names to the signature before passing it to `w3.NewFunc` but it led me down the path of parsing the signature, replicating a lot of what `w3` is already doing, so it seemed more natural to do it in the library instead.

However -- if `Arguments.Unpack` provides what I need, I'd be happy to revise my PR to remove the `[]any` decoding part, if you prefer not having that in `w3`.

**Comment by lmittmann** [comment]
> I did try adding dummy arg names to the signature before passing it to w3.NewFunc but it led me down the path of parsing the signature myself, replicating a lot of what w3 is already doing, so it seemed more natural to do it in the library instead.

I would probably just go for a regex that searches types that are not followed by a variable name and than add the dummy arg behind it.

**Comment by joel-u410** [comment]
It looks like `Arguments.UnpackValues` will provide what I need. I'll split up the "decode into `[]any`" part of my PR into a separate one so each feature can be merged (or not) on its own.

**Comment by lmittmann** [comment]
I appreciate the effort, but I don't want to add the decoding of tuples into slices to the package.

**Comment by joel-u410** [comment]
Are you ok with merging the support for unnamed tuples, without decoding into slices, if it were to work like this?

```go
{
	// https://github.com/lmittmann/w3/issues/67
	Func:  w3.MustNewFunc("test((address, uint256))", ""),
	Input: w3.B("0xba71720c000000000000000000000000000000000000000000000000000000000000c0fe000000000000000000000000000000000000000000000000000000000000002a"),
	Args:  []any{new(tuple)},
	WantArgs: []any{&tuple{
		Arg0: w3.A("0x000000000000000000000000000000000000c0Fe"),
		Arg1: big.NewInt(42),
	}},
},
```

**Comment by lmittmann** [comment]
yes!

**Comment by joel-u410** [comment]
OK -- I'll have that pushed up shortly 😄

**Comment by joel-u410** [comment]
Just updated the branch, please have a look.
