### ISSUE TITLE
Add support for L2 networks like Arbitrum/Optimism

### ISSUE THREAD

**Issue by antonydenyer** [lmittmann/w3#71]
Many L2s have differences from the standard rpc endpoints available in geth. In most cases, I don't this is an issue, additional fields and the like, are ignored during serialization.

https://docs.arbitrum.io/arbitrum-ethereum-differences#json-rpc-api

For example, Optimism and Arbitrum have some additional transaction types that do not break the rpc spec but do break when serializing into geth types. 

For example:

`client.CallCtx(ctx, eth.BlockByNumber(head).Returns(block))`

will return 

`panic: w3: call failed: transaction type not supported`

**Comment by lmittmann** [comment]
I am aware of these issues, but have currently no plan to improve support as this is out of scope. Something you can try is replacing the go-ethereum dependency with your go-ethereum fork of choice in your projects `go.mod`. This might work, but could also lead to conflicts depending on how big its codebase diverges from go-ethereum.

**Comment by antonydenyer** [comment]
I am OK with doing the work to improve things. Most of it is just how it's serialized into the structs. There's a reason geth has a bunch of internal types and whatnot (e.g `ethapi.RPCTransaction`) unfortunately, there's no consistency in there either. 

Should a client library be validating responses from an API?
