### ISSUE TITLE
How to get errors back with w3 api?

### ISSUE THREAD

**Issue by kant777** [lmittmann/w3#84]
How can I get error back with this interface/api? for example say I want to do this 

```
var latestBlockNumber big.Int
eth.BlockNumber().Returns(&latestBlockNumber)
```
what happens if this network call fails? would the block number be -1 or something? I can `eth.BlockNumber().Returns(&latestBlockNumber).createRequest()` but then I am batch BatchElem and ethClient API which is not great. The w3 API looks really good and would be nice if it can also returns errors

**Comment by lmittmann** [comment]
`eth.BlockNumber()...` will just generate the RPC call. You also need a client to send the call to some endpoint and that client returns the error (see https://github.com/lmittmann/w3#batch-requests). If you send multiple calls in a single request and one is failing you can use https://pkg.go.dev/github.com/lmittmann/w3#CallErrors to get the error per RPC call.
